runtime: php74

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /images
  static_dir: images
- url: /modolingo\.css
  static_files: modolingo\.css
  upload: modolingo\.css
- url: /validate\.js
  static_files: /validate\.js
  upload: /validate\.js
- url: .*
  script: auto

env_variables:
  STORAGE_BUCKET: "macro-thinker-261715.appspot.com"
