<?php
$responses=array(1=>'a','b','c','d');

$language_lower="englisch";
$language_upper="Englisch";
$title="Einstufungstest f&uuml;r Business English";
$question_word="Question";

$q[1][1]="A: Is this the right place for British Airways?";
$q[1][2]="B: Yes, it _____.";

$o[1][1]="isn't";
$o[1][2]="are";
$o[1][3]="is it";
$o[1][4]="is";

$q[2][1]="Roger is _____ Switzerland.";

$o[2][1]="a with";
$o[2][2]="from";
$o[2][3]="not";
$o[2][4]="a";

$q[3][1]="A: Do you smoke?";
$q[3][2]="B: No, I _____.";

$o[3][1]="don't";
$o[3][2]="'m not";
$o[3][3]="not";
$o[3][4]="doesn't";

$q[4][1]="A: _____ does he work?";
$q[4][2]="B: In a hospital.";

$o[4][1]="Why";
$o[4][2]="When";
$o[4][3]="What";
$o[4][4]="Where";

$q[5][1]="How _____ do they play golf?";

$o[5][1]="usually";
$o[5][2]="every";
$o[5][3]="often";
$o[5][4]="time";

$q[6][1]="Are there _____ messages for me?";

$o[6][1]="got";
$o[6][2]="any";
$o[6][3]="a";
$o[6][4]="have";

$q[7][1]="I'm afraid I can't _____ the meeting at three.";

$o[7][1]="to make";
$o[7][2]="made";
$o[7][3]="make";
$o[7][4]="making";

$q[8][1]="He _____ in when I rang.";

$o[8][1]="wasn't";
$o[8][2]="isn't";
$o[8][3]="weren't";
$o[8][4]="didn't";

$q[9][1]="Henry _____ school at fifteen.";

$o[9][1]="has left";
$o[9][2]="leave";
$o[9][3]="left";
$o[9][4]="leaved";

$q[10][1]="A: When _____ he phone?";
$q[10][2]="B: At around three.";

$o[10][1]="was";
$o[10][2]="time";
$o[10][3]="did";
$o[10][4]="do";

$q[11][1]="How _____ time off do you get a year?";

$o[11][1]="many";
$o[11][2]="much";
$o[11][3]="any";
$o[11][4]="some";

$q[12][1]="It's hotter today _____ yesterday.";

$o[12][1]="as";
$o[12][2]="the";
$o[12][3]="more";
$o[12][4]="than";

$q[13][1]="I travel to work _______ motorbike.";

$o[13][1]="with";
$o[13][2]="on";
$o[13][3]="by";
$o[13][4]="from";

$q[14][1]="I _____ on an important project at the moment.";

$o[14][1]="going to work";
$o[14][2]="worked";
$o[14][3]="work";
$o[14][4]="'m working";

$q[15][1]="I _____ the report yet. I need a couple more hours.";

$o[15][1]="didn't finish";
$o[15][2]="don't finish";
$o[15][3]="haven't finished";
$o[15][4]="'m not finishing";

$q[16][1]="I _____ a profit this year.";

$o[16][1]="set up";
$o[16][2]="made";
$o[16][3]="did";
$o[16][4]="ran";

$q[17][1]="A: Can I have extension 315?";
$q[17][2]="B: I'll just _____ you through.";

$o[17][1]="put";
$o[17][2]="hold";
$o[17][3]="call";
$o[17][4]="play";

$q[18][1]="Could I _____ a message?";

$o[18][1]="speak";
$o[18][2]="leave";
$o[18][3]="tell";
$o[18][4]="say";

$q[19][1]="A: What's he like?";
$q[19][2]="B: He _______________________";

$o[19][1]="works for the National Bank of Poland.";
$o[19][2]="'s the Public Relations Manager";
$o[19][3]="'s a nice man.";
$o[19][4]="plays golf.";

$q[20][1]="A: Hello, I am Brian Miller.";
$q[20][2]="B: ____________________________";

$o[20][1]="Hello, pleased to meet you.";
$o[20][2]="I'm pleased too.";
$o[20][3]="Nice to have met you.";
$o[20][4]="Good to see you too.";

$q[21][1]="Who __________the first e-mail?";

$o[21][1]="did send";
$o[21][2]="did happen";
$o[21][3]="sent";
$o[21][4]="was sent";

$q[22][1]="I'll _____ with the e-mail straight away.";

$o[22][1]="send";
$o[22][2]="deal";
$o[22][3]="go";
$o[22][4]="write";

$q[23][1]="It's the _____ meal I've ever eaten!";

$o[23][1]="expensive than";
$o[23][2]="more expensive";
$o[23][3]="expensivest";
$o[23][4]="most expensive";

$q[24][1]="I'll have breakfast sent _____ to your room.";

$o[24][1]="up";
$o[24][2]="out of";
$o[24][3]="in";
$o[24][4]="at";

$q[25][1]="Prices have remained _____ in the first quarter.";

$o[25][1]="increase";
$o[25][2]="stable";
$o[25][3]="same";
$o[25][4]="steadily";

$q[26][1]="I'm writing to _____ the refund for damaged goods.";

$o[26][1]="claim";
$o[26][2]="tackle";
$o[26][3]="take";
$o[26][4]="book";

$q[27][1]="35,000 people _____ in the last five years.";

$o[27][1]="were been laid off";
$o[27][2]="lay off";
$o[27][3]="are laid off";
$o[27][4]="have been laid off";

$q[28][1]="It costs one hundred euros! What a complete _____ of money.";

$o[28][1]="invest";
$o[28][2]="spent";
$o[28][3]="waste";
$o[28][4]="lot";

$q[29][1]="He _____ me that he was happy in his new department.";

$o[29][1]="said";
$o[29][2]="told";
$o[29][3]="speak";
$o[29][4]="asked";

$q[30][1]="We _____ less time traveling, if we worked from home.";

$o[30][1]="spend";
$o[30][2]="would spend";
$o[30][3]="will spend";
$o[30][4]="are spending";

$q[31][1]="Does the conference centre have internet _____?";

$o[31][1]="access";
$o[31][2]="location";
$o[31][3]="centre";
$o[31][4]="transfer";

$q[32][1]="Sorry, I didn't _____ that. Could you say it again?";

$o[32][1]="not with";
$o[32][2]="explain";
$o[32][3]="catch";
$o[32][4]="miss";

$q[33][1]="Would you mind _____ , please?";

$o[33][1]="not to smoke";
$o[33][2]="not smoking";
$o[33][3]="didn't smoking";
$o[33][4]="if not smoking";

$q[34][1]="You _____ be tired after your long journey.";

$o[34][1]="can";
$o[34][2]="let";
$o[34][3]="must";
$o[34][4]="ought";

$q[35][1]="I agree with you up to a _____.";

$o[35][1]="question";
$o[35][2]="position";
$o[35][3]="point";
$o[35][4]="view";

$q[36][1]="_____ I thought everyone knew.";

$o[36][1]="Won't you hear?";
$o[36][2]="Haven't you heard?";
$o[36][3]="Didn't you hear?";
$o[36][4]="Aren't you hearing?";

$q[37][1]="Let's move _____ to the next point of my presentation.";

$o[37][1]="about";
$o[37][2]="up";
$o[37][3]="for";
$o[37][4]="on";

$q[38][1]="Do you know if they have _________ me a meeting room?";

$o[38][1]="booked";
$o[38][2]="got";
$o[38][3]="gathered";
$o[38][4]="collected";

$q[39][1]="So, let's sum _____ what we've discussed so far.";

$o[39][1]="about";
$o[39][2]="up";
$o[39][3]="with";
$o[39][4]="for";

$q[40][1]="I _____ from you.";

$o[40][1]="look forward to hear";
$o[40][2]="looking forward to hearing";
$o[40][3]="look forward to hearing";
$o[40][4]="look forward for hearing";

$q[41][1]="How are things _____ you?";

$o[41][1]="with";
$o[41][2]="to";
$o[41][3]="at";
$o[41][4]="of";

$q[42][1]="In France, cheese is normally ________ after dessert.";

$o[42][1]="bring";
$o[42][2]="served";
$o[42][3]="asked";
$o[42][4]="invited";

$q[43][1]="I'm sorry for the _____ in getting back to you with the quote.";

$o[43][1]="wait";
$o[43][2]="hold";
$o[43][3]="late";
$o[43][4]="delay";

$q[44][1]="I suggested _____ the whole thing forward by a week.";

$o[44][1]="bringing";
$o[44][2]="to bring";
$o[44][3]="that bring";
$o[44][4]="we bringing";

$q[45][1]="With _____ , I think that's a little too low.";

$o[45][1]="frank";
$o[45][2]="respect";
$o[45][3]="honesty";
$o[45][4]="unfortunately";

$q[46][1]="_____ , no see. You haven't changed a bit!";

$o[46][1]="Long time";
$o[46][2]="Long wait";
$o[46][3]="Long listen";
$o[46][4]="Long view";

$q[47][1]="Are you saying they've fallen _____ of projections again?";

$o[47][1]="down";
$o[47][2]="decrease";
$o[47][3]="short";
$o[47][4]="rapidly";

$q[48][1]="It was a very _____ meeting in the end.";

$o[48][1]="achievement";
$o[48][2]="smoothly";
$o[48][3]="success";
$o[48][4]="fruitful";

$q[49][1]="I've just _____ a job with Bill Gates!";

$o[49][1]="landed";
$o[49][2]="run";
$o[49][3]="set";
$o[49][4]="caught";

$q[50][1]="Can I get hold _____ the organizers?";

$o[50][1]="to";
$o[50][2]="of";
$o[50][3]="for";
$o[50][4]="up";

$a[1]="d";
$a[2]="b";
$a[3]="a";
$a[4]="d";
$a[5]="c";
$a[6]="b";
$a[7]="c";
$a[8]="a";
$a[9]="c";
$a[10]="c";
$a[11]="b";
$a[12]="d";
$a[13]="c";
$a[14]="d";
$a[15]="c";
$a[16]="b";
$a[17]="a";
$a[18]="b";
$a[19]="c";
$a[20]="a";
$a[21]="c";
$a[22]="b";
$a[23]="d";
$a[24]="a";
$a[25]="b";
$a[26]="a";
$a[27]="d";
$a[28]="c";
$a[29]="b";
$a[30]="b";
$a[31]="a";
$a[32]="c";
$a[33]="b";
$a[34]="c";
$a[35]="c";
$a[36]="b";
$a[37]="d";
$a[38]="a";
$a[39]="b";
$a[40]="c";
$a[41]="a";
$a[42]="b";
$a[43]="d";
$a[44]="a";
$a[45]="b";
$a[46]="a";
$a[47]="c";
$a[48]="d";
$a[49]="a";
$a[50]="b";
?>
