<?php
$responses=array(1=>'a','b','c','d');

$language_lower="französisch";
$language_upper="Französisch";
$title="Einstufungstest f&uuml;r Französisch";
$question_word="Question";

$q[1][1]="Bonjour, comment ______ -vous ?";

$o[1][1]="va";
$o[1][2]="vont";
$o[1][3]="avez";
$o[1][4]="allez";

$q[2][1]="Il habite __ Paris.";

$o[2][1]="de";
$o[2][2]="à";
$o[2][3]="en";
$o[2][4]="au";

$q[3][1]="Je m’appelle Pierre. Et toi tu __ appelles comment ?";

$o[3][1]="t’";
$o[3][2]="m’";
$o[3][3]="s’";
$o[3][4]="vous";

$q[4][1]="Moi, je m’appelle Marion. Et ___, il s’appelle comment ?";

$o[4][1]="toi";
$o[4][2]="elle";
$o[4][3]="eux";
$o[4][4]="lui";

$q[5][1]="Elles _______ françaises. Et toi, tu ________ français ?";

$o[5][1]="est;es";
$o[5][2]="sont;ai";
$o[5][3]="sont;es";
$o[5][4]="est;est";

$q[6][1]="Victor ___ 18 ans.";

$o[6][1]="à";
$o[6][2]="a";
$o[6][3]="est";
$o[6][4]="ai";

$q[7][1]="Je ____ parle ____ japonais.";

$o[7][1]="ni … ni";
$o[7][2]="ne … de";
$o[7][3]="ne … pas";
$o[7][4]="ni … que";

$q[8][1]="Qu’est-ce que tu ______ ?";

$o[8][1]="aimes";
$o[8][2]="aime";
$o[8][3]="aimer";
$o[8][4]="aimez";

$q[9][1]="Je vais ____ Musée d’Orsay..";

$o[9][1]="à le";
$o[9][2]="en";
$o[9][3]="au";
$o[9][4]="dans";

$q[10][1]="____ est le Musée d’Orsay s’il vous plait ?";

$o[10][1]="Quand";
$o[10][2]="Quoi";
$o[10][3]="Où";
$o[10][4]="Ou";

$q[11][1]="Nous allons au cinéma. Tu _____ aussi ?";

$o[11][1]="vient";
$o[11][2]="viens";
$o[11][3]="vends";
$o[11][4]="venez";

$q[12][1]="Ça fait __________ ? Ça fait 10 € s’il vous plait.";

$o[12][1]="qui";
$o[12][2]="comment";
$o[12][3]="quoi";
$o[12][4]="combien";

$q[13][1]="Je vais acheter ___ pain.";

$o[13][1]="un";
$o[13][2]="de la";
$o[13][3]="du";
$o[13][4]="de le";

$q[14][1]="Vous êtes combien ? ____ est quatre.";

$o[14][1]="Elle";
$o[14][2]="Il";
$o[14][3]="Vous";
$o[14][4]="On";

$q[15][1]="Nous _______ le travail à 18h.";

$o[15][1]="finit";
$o[15][2]="finissez";
$o[15][3]="finissons";
$o[15][4]="finissent";

$q[16][1]="________ tu as des enfants ?";

$o[16][1]="Que";
$o[16][2]="Est-ce que";
$o[16][3]="Es-ce que";
$o[16][4]="Combien";

$q[17][1]="Je _______ apprendre le français.";

$o[17][1]="veux";
$o[17][2]="veus";
$o[17][3]="voulois";
$o[17][4]="veut";

$q[18][1]="En été il _____ chaud.";

$o[18][1]="est";
$o[18][2]="fait";
$o[18][3]="faut";
$o[18][4]="fais";

$q[19][1]="Il habite ___ France mais il travaille ___ Luxembourg.";

$o[19][1]="à la;au";
$o[19][2]="en;à le";
$o[19][3]="en;au";
$o[19][4]="en;en";

$q[20][1]="Julien ______ à New York en 1982.";

$o[20][1]="est allé";
$o[20][2]="a allé";
$o[20][3]="va";
$o[20][4]="est allés";

$q[21][1]="Hier je _________ Mme Dupont à la poste.";

$o[21][1]="est rencontré";
$o[21][2]="suis rencontré";
$o[21][3]="ai rencontré";
$o[21][4]="rencontre";

$q[22][1]="_______ est la nationalité de Jean ? ";

$o[22][1]="Quel";
$o[22][2]="Quelle";
$o[22][3]="Quelles";
$o[22][4]="Quels";

$q[23][1]="Pour ____ anniversaire, j’ai invité ____ amis.";

$o[23][1]="ma;mon";
$o[23][2]="mon;mon";
$o[23][3]="mon;ma";
$o[23][4]="mon;mes";

$q[24][1]="Anne et Pierre je ne ___ connais pas mais Marie je ___ connais.";

$o[24][1]="les;la";
$o[24][2]="eux;elle";
$o[24][3]="le;le";
$o[24][4]="la;la";

$q[25][1]="La semaine prochaine je _____ partir en vacances.";

$o[25][1]="viens";
$o[25][2]="vais";
$o[25][3]="suis";
$o[25][4]="ai";

$q[26][1]="Elle lit beaucoup mais elle ___ regarde ________ la télévision.";

$o[26][1]="ne … jamais";
$o[26][2]="ni … ni";
$o[26][3]="ne … toujours";
$o[26][4]="ne … que";

$q[27][1]="La ville de Paris est _____ grande ____ la ville de Lyon.";

$o[27][1]="plus … de";
$o[27][2]="aussi … que";
$o[27][3]="moins … que";
$o[27][4]="plus … que";

$q[28][1]="Marseille est une grande ville mais Paris est ________ grande ville ___ France.";

$o[28][1]="plus … que";
$o[28][2]="la plus … de";
$o[28][3]="le plus … de";
$o[28][4]="plus … de";

$q[29][1]="Marie et Pierre vont _____ marier en septembre. Nous allons aussi _____ marier en Septembre";

$o[29][1]="se;se";
$o[29][2]="eux;nous";
$o[29][3]="se;nous";
$o[29][4]="eux;se";

$q[30][1]="Jean est discret et réservé : il est ___________.";

$o[30][1]="bavard";
$o[30][2]="timide";
$o[30][3]="gourmand";
$o[30][4]="élégant";

$q[31][1]="A: Tu as acheté le journal?";
$q[31][2]="B: Oui, je _______________________ de le lire";  

$o[31][1]="suis en train";
$o[31][2]="vais";
$o[31][3]="ai en train";
$o[31][4]="veux";

$q[32][1]="A: Je suis abonné au journal Le Monde.  Je le lis ______ les jours.";

$o[32][1]="toutes";
$o[32][2]="tout";
$o[32][3]="tous";
$o[32][4]="toute";

$q[33][1]="A: Je veux parler à Pierre s’il vous plait ?";
$q[33][2]="B: Il n’est pas là. Vous ne pouvez pas _____ parler."; 

$o[33][1]="il";
$o[33][2]="lui";
$o[33][3]="à lui";
$o[33][4]="à il";

$q[34][1]="Elle a le coeur sur la main:";

$o[34][1]="Elle est timide";
$o[34][2]="Elle est folle";
$o[34][3]="Elle est généreuse";
$o[34][4]="Elle est malade";

$q[35][1]="Quand je _______ 10 ans, je ________ dans un petit village.";

$o[35][1]="ai eu; ai habité";
$o[35][2]="ai eu; habitais";
$o[35][3]="avais; ai habité";
$o[35][4]="avais; habitais";

$q[36][1]="Avant il ______  employé dans une grande entreprise, mais en 1975 l’entreprise ______ faillite.";

$o[36][1]="a été;faisait";
$o[36][2]="était;a fait";
$o[36][3]="a été;a fait";
$o[36][4]="était;faisait";

$q[37][1]="Quand le téléphone ______, je ______ le journal";

$o[37][1]="sonnait;lisais";
$o[37][2]="sonnait;ai lu";
$o[37][3]="a sonné;ai lu";
$o[37][4]="a sonné;lisais";

$q[38][1]="J’ai une voiture très rapide mais je ne conduis pas ____________.";

$o[38][1]="rapidamment";
$o[38][2]="rapideusement";
$o[38][3]="rapide";
$o[38][4]="rapidement";

$q[39][1]="Marie est une jeune femme, _____ a l’air timide.";

$o[39][1]="que";
$o[39][2]="qui";
$o[39][3]="où";
$o[39][4]="dont";

$q[40][1]="Elle est allée à la bibliothèque chercher un livre. Elle __ est restée toute la journée.";

$o[40][1]="en";
$o[40][2]="à";
$o[40][3]="y";
$o[40][4]="là";

$q[41][1]="Elle a passé toute la journée à la piscine. Elle ___ est revenue très fatiguée.";

$o[41][1]="en";
$o[41][2]="de";
$o[41][3]="y";
$o[41][4]="là-bas";

$q[42][1]="Si je _______ riche, je ________ une maison sur la Côte d’Azur";

$o[42][1]="ai été;achetais";
$o[42][2]="étais;achèterais";
$o[42][3]="suis ;achèterais";
$o[42][4]="étais ;achèterai";

$q[43][1]="Il habite à Vienne ____________ 2 ans.Je ne l’ai pas vu ___________________ il est à Vienne.";

$o[43][1]="depuis;depuis";
$o[43][2]="depuis que;depuis ";
$o[43][3]="pendant;pendant";
$o[43][4]="depuis;depuis que";

$q[44][1]="________________ une heure ______ je t’attends.";

$o[44][1]="Ça fait … que";
$o[44][2]="Pendant … que";
$o[44][3]="Depuis … que";
$o[44][4]="C’est … que";

$q[45][1]="Il a vécu en Allemagne ____________ 3 ans. Il a appris l’allemand _______ 2 mois.";

$o[45][1]="depuis;depuis";
$o[45][2]="pendant;en";
$o[45][3]="ça fait;dans";
$o[45][4]="pendant;dans";

$q[46][1]="Marie et Pierre ne sont jamais contents. Ils ________ tout le temps!";

$o[46][1]="se plaignent";
$o[46][2]="se plainent";
$o[46][3]="se plaigne";
$o[46][4]="se plaindent";

$q[47][1]="A: Pourquoi n’a tu pas mis ta nouvelle robe ?";
$q[47][2]="B: Je ____________ parce qu’elle ne me plait pas.";

$o[47][1]="ne l’ai pas mis";
$o[47][2]="ne les ai pas mis";
$o[47][3]="ne l’ai pas mise";
$o[47][4]="ne les ai pas mise";

$q[48][1]="Il faut que tu ______ du sport et que tu ________ des fruits et des légumes. ";

$o[48][1]="fais;manges";
$o[48][2]="faisais;mangeais";
$o[48][3]="ferais;mangerais";
$o[48][4]="fasses;manges";

$q[49][1]="Je voudrais que tu ________ plus gentille avec ta grand-mère.";

$o[49][1]="sois";
$o[49][2]="est";
$o[49][3]="serais";
$o[49][4]="serai";

$q[50][1]="Dans une semaine nous __________ en vacances.";

$o[50][1]="soyons";
$o[50][2]="serons";
$o[50][3]="sont";
$o[50][4]="êtrons";











$a[1]="d";
$a[2]="b";
$a[3]="a";
$a[4]="d";
$a[5]="c";
$a[6]="b";
$a[7]="c";
$a[8]="a";
$a[9]="c";
$a[10]="c";
$a[11]="b";
$a[12]="d";
$a[13]="c";
$a[14]="d";
$a[15]="c";
$a[16]="b";
$a[17]="a";
$a[18]="b";
$a[19]="c";
$a[20]="a";
$a[21]="c";
$a[22]="b";
$a[23]="d";
$a[24]="a";
$a[25]="b";
$a[26]="a";
$a[27]="d";
$a[28]="b";
$a[29]="b";
$a[30]="b";
$a[31]="a";
$a[32]="c";
$a[33]="b";
$a[34]="c";
$a[35]="c";
$a[36]="b";
$a[37]="d";
$a[38]="a";
$a[39]="b";
$a[40]="c";
$a[41]="a";
$a[42]="b";
$a[43]="d";
$a[44]="a";
$a[45]="b";
$a[46]="a";
$a[47]="c";
$a[48]="d";
$a[49]="a";
$a[50]="b";

?>
