<?php
$responses=array(1=>'a','b','c','d');

$language_lower="deutsch";
$language_upper="Deutsch";
$target_langDE="Deutsch";
$title="Einstufungstest f&uuml;r Deutsch";
$question_word="Frage";

$q[1][1]="A: Hallo, ich heiße Anna. Und wer ___________ du?";
$q[1][2]="B: David.";

$o[1][1]="heißt"; 
$o[1][2]="bin";
$o[1][3]="sein";
$o[1][4]="bist";

$q[2][1]="Das ist Anna. Sie kommt ______ Italien.";

$o[2][1]="von";
$o[2][2]="aus";
$o[2][3]="in";
$o[2][4]="mit";

$q[3][1]="A: Sprichst du Deutsch?";    
$q[3][2]="B: Nein, ich spreche _______________. ";

$o[3][1]="Englisch";
$o[3][2]="'Deutsch";
$o[3][3]="in Englisch";
$o[3][4]="mit Englisch";

$q[4][1]="A: ______________ist dein Beruf?";   
$q[4][2]="B: Ich arbeite ___________Koch.";

$o[4][1]="Wo…bei";
$o[4][2]="Wann…als";
$o[4][3]="Woher…bei";
$o[4][4]="Was…als";

$q[5][1]="A: ____________du schon mal in Bremerhaven?";   
$q[5][2]="B: Nein, wo ist das?";

$o[5][1]="bist";
$o[5][2]="hast";
$o[5][3]="warst";
$o[5][4]="wärest";

$q[6][1]="A: Um _____ Uhr stehst du am Montag auf?";
$q[6][2]="B: Um 07:00 Uhr.";

$o[6][1]="wann";
$o[6][2]="wie viel";
$o[6][3]="wie spät";
$o[6][4]="wo";

$q[7][1]="A: Mama, kaufst du _____ ein Eis?";
$q[7][2]="B: Nein, heute bekommst du kein Eis.";

$o[7][1]="ihr";
$o[7][2]="dir";
$o[7][3]="mir";
$o[7][4]="euch";

$q[8][1]="A: Hast du _____ Hund?";
$q[8][2]="B: Nein, ich habe ___________ Hund.";

$o[8][1]="einen…keinen";
$o[8][2]="ein…nicht";
$o[8][3]="ein…kein";
$o[8][4]="eine…keine";

$q[9][1]="A: Kennst du diesen Mann?";
$q[9][2]="B: Ja, ich glaube ich habe ___________ schon einmal gesehen.";

$o[9][1]="ihm";
$o[9][2]="es";
$o[9][3]="ihn";
$o[9][4]="Ihnen";

$q[10][1]="A:Ich esse gerne Nudeln.";
$q[10][2]="B: Ich esse _____ Pizza _______ Nudeln.";

$o[10][1]="gerne ... als";
$o[10][2]="am ... liebsten";
$o[10][3]="lieber ... als";
$o[10][4]="lieber ... wie";

$q[11][1]="A: Papa, kaufst _____ _____ Süßigkeiten?";
$q[11][2]="B: Nein, heute nicht.";

$o[11][1]="du ... mich";
$o[11][2]="du ... mir";
$o[11][3]="du ... dich";
$o[11][4]="ihr ... euch";

$q[12][1]="A: Grüß Gott, wann haben Sie Sprechstunde?";
$q[12][2]="B: Am Freitag _____ 08:30 ________ 12:00 Uhr?";

$o[12][1]="am ... bis";
$o[12][2]="um ... bis";
$o[12][3]="am ... um";
$o[12][4]="von ... bis";

$q[13][1]="A: Magst du Autos?";
$q[13][2]="B: Oh ja, ich interessiere _______ sehr dafür.";

$o[13][1]="mir";
$o[13][2]="dich";
$o[13][3]="mich";
$o[13][4]="dir";

$q[14][1]="A: Leben deine Großeltern noch?";
$q[14][2]="B: Meine _____ lebt noch. Mein ________ leider nicht mehr.";

$o[14][1]="Schwester ... Bruder";
$o[14][2]="Mama ... Papa";
$o[14][3]="Opa ... Oma";
$o[14][4]="Oma ... Opa";

$q[15][1]="A: Gehen wir morgen ins Kino?";
$q[15][2]="B: Nein, dass geht leider nicht! Ich _______ lernen.";

$o[15][1]="kann";
$o[15][2]="darf";
$o[15][3]="muss";
$o[15][4]="müssen";

$q[16][1]="Meine Kollegin hat mir einen Blumenstrauß geschenkt. Ich habe ___ sehr ___ die Blumen ___?";

$o[16][1]="mir ... über ... gefreut";
$o[16][2]="mich ... über ... gefreut";
$o[16][3]="mich ... mit ... gefreut";
$o[16][4]="mich ... über ... freuen";

$q[17][1]="A: Hallo Holger, wie war dein Wochenende?";
$q[17][2]="B: Geht so, ich _____ ein Fußballspiel.";

$o[17][1]="hatte";
$o[17][2]="war";
$o[17][3]="habe";
$o[17][4]="machte";

$q[18][1]="Tina feiert heute Geburtstag. Sie hat gefragt, _______ du kommst.";

$o[18][1]="weil";
$o[18][2]="ob";
$o[18][3]="dass";
$o[18][4]="da";

$q[19][1]="Schon mein Großvater _______ Bäcker und _______ in einer Bäckerei in Berlin.";

$o[19][1]="ist ... arbeitet";
$o[19][2]="war ... arbeitet";
$o[19][3]="war ... arbeitete";
$o[19][4]="ist ... arbeitete";

$q[20][1]="A: Wo ist denn bloß die DVD?";
$q[20][2]="B: Die DVD liegt ______ Tisch. Ich stelle sie _______ Regal.";

$o[20][1]="auf dem ... in das";
$o[20][2]="auf den ... in das";
$o[20][3]="in dem  ... auf das";
$o[20][4]="auf dem ... auf den";

$q[21][1]="A: Vergiss nicht die Wäsche _________ !";
$q[21][2]="B: Aber ich habe sie schon _______ .";

$o[21][1]="zu waschen ... geputzt";
$o[21][2]="waschen ... gewaschen";
$o[21][3]="zu waschen ... gewaschen";
$o[21][4]="zu putzen ... geputzt";

$q[22][1]="A: Ich habe Sie nicht verstanden.";
$q[22][2]="B: ______ Sie bitte langsamer sprechen?";

$o[22][1]="Sollten";
$o[22][2]="Könnten";
$o[22][3]="Müssten";
$o[22][4]="Kannst";

$q[23][1]="A: Anna hat viel mit ihrem Handy telefoniert.";
$q[23][2]="B: Sie hat ___ ___ Kosten zu rechnen."; 

$o[23][1]="durch ... hohe";
$o[23][2]="mit ... hoher";
$o[23][3]="einer ... hohen";
$o[23][4]="mit ... hohen";

$q[24][1]="Ich bin sehr müde, _____ gehe ich heute früher ins Bett";

$o[24][1]="deshalb";
$o[24][2]="weil";
$o[24][3]="dass";
$o[24][4]="während";

$q[25][1]="A: Der Winter 1946 war der kälteste Winter in Deutschland?";
$q[25][2]="B: Das stimmt nicht. __________ der Winter 1946, __________ der Winter 1829 war der kälteste Winter in Deutschland.";

$o[25][1]="weder ... sondern";
$o[25][2]="nicht ... sondern";
$o[25][3]="nicht ... desto";
$o[25][4]="je ... sondern";

$q[26][1]="A: Wohnst du alleine?";
$q[26][2]="B: Nein, ich wohne im Haus ______ Mutter.";

$o[26][1]="meiner";
$o[26][2]="meine";
$o[26][3]="meines";
$o[26][4]="mir";

$q[27][1]="A: Hast du Paul gesehen?";
$q[27][2]="B: Nein, ich habe ihn _____ 3 Tagen nicht mehr gesehen.";

$o[27][1]="während";
$o[27][2]="sein";
$o[27][3]="durch";
$o[27][4]="seit";

$q[28][1]="A: ______ freuen Sie sich?";
$q[28][2]="B: ______ eine bestandene Prüfung.";

$o[28][1]="Wodurch ... Mit";
$o[28][2]="Wofür ... Über";
$o[28][3]="Worüber ... Über";
$o[28][4]="Wovon ... Von";

$q[29][1]="Nachdem wir  ____ ____ , sah die Küche sehr schmutzig aus.";

$o[29][1]="gekocht ... haben";
$o[29][2]="gekocht ... hatten";
$o[29][3]="kochen ... hatten";
$o[29][4]="kochen ... haben";

$q[30][1]="A: Ich finde die Strände in Italien zu voll?";
$q[30][2]="B: Ich auch. ___________fahre ich immer wieder gerne hin.";

$o[30][1]="deshalb";
$o[30][2]="trotzdem";
$o[30][3]="dafür";
$o[30][4]="deswegen";

$q[31][1]="A: Was ____ du gerne kaufen?";
$q[31][2]="B: Ich _____mir gerne ein Kleid kaufen.";


$o[31][1]="würdest ... würde";
$o[31][2]="würdest ... wäre";
$o[31][3]="willst ... will";
$o[31][4]="solltest ... sollte";

$q[32][1]="_____Schwimmen fühlt man sich, _____man schwerelos wäre.";

$o[32][1]="beim ... wie das";
$o[32][2]="das ... als ob";
$o[32][3]="beim ... als ob";
$o[32][4]="beim ... als wäre man";

$q[33][1]="A: Mein Auto ist kaputt.";
$q[33][2]="B: Es _____ am Montag ______.";

$o[33][1]="ist ... repariert";
$o[33][2]="wird ... repariert";
$o[33][3]="war ... repariert";
$o[33][4]="sind ... repariert";

$q[34][1]="A: Haben Sie das neueste Handy - Modell?";
$q[34][2]="B: Kommen Sie, ich zeige _____ Ihnen.";


$o[34][1]="das";
$o[34][2]="Handy - Modell";
$o[34][3]="es";
$o[34][4]="den";

$q[35][1]="A: Wie war euer Urlaub?";
$q[35][2]="B: Obwohl es_____, _____es schön.";

$o[35][1]="regnet ... war";
$o[35][2]="schön war ... war";
$o[35][3]="regnete ... war";
$o[35][4]="regnet ... ist";

$q[36][1]="A: Was genau wollte er denn wissen?";
$q[36][2]="B: Er wollte wissen, _____ ich in diesem Bereich schon einmal tätig war.";

$o[36][1]="dass";
$o[36][2]="ob";
$o[36][3]="obwohl";
$o[36][4]="weil";

$q[37][1]="A: Erinnern Sie sich an den Termin?";
$q[37][2]="B: Ja, _____ erinnere ich ______.";

$o[37][1]="dafür…mich";
$o[37][2]="darüber…mich";
$o[37][3]="daran…mir";
$o[37][4]="daran…mich";

$q[38][1]="A: Wofür interessierst du dich?";
$q[38][2]="B: ______ Mathematik und Physik.";

$o[38][1]="Für";
$o[38][2]="Nach";
$o[38][3]="Über";
$o[38][4]="An";

$q[39][1]="A: Welches Haus wird abgerissen?";
$q[39][2]="B: Das Haus ___ Mauer beschädigt ist.";


$o[39][1]="wo";
$o[39][2]="dessen";
$o[39][3]="die";
$o[39][4]="den";

$q[40][1]="Die Menschen aus der DDR übten Druck auf die Regierung aus, ______ sie Massenproteste organisierten.";

$o[40][1]="dass";
$o[40][2]="dadurch";
$o[40][3]="indem";
$o[40][4]="weil";

$q[41][1]="Die Bundesregierung ______, den Anbau gentechnisch veränderterer Pflanzen unter strengere Gesetze zu stellen.";

$o[41][1]="hat die Absicht";
$o[41][2]="will";
$o[41][3]="möchte";
$o[41][4]="kann";

$q[42][1]="Kommt es ______Einbruch, sind die Banken geneigt, den Schaden zu ersetzen, auch wenn sie keine Schuld trifft";

$o[42][1]="beim";
$o[42][2]="zum";
$o[42][3]="als";
$o[42][4]="dem";

$q[43][1]="A: Seit 2 Stunden klingelt das Telefon?";
$q[43][2]="B: Ja, ___ ___ ___ die Nerven.";

$o[43][1]="geht ... mich ... an";
$o[43][2]="geht ... mir ... an";
$o[43][3]="kann ... mir ... auf";
$o[43][4]="geht ... mir ... auf";

$q[44][1]="Gestern war ich im Zirkus und habe einen ______________ Bären gesehen.";

$o[44][1]="tanzenden";
$o[44][2]="getanzten";
$o[44][3]="tanzen";
$o[44][4]="tanzend";

$q[45][1]="A: Veni, vidi, vici!";
$q[45][2]="B: Das ist ein oft ___________Sprichwort.";

$o[45][1]="zitierend";
$o[45][2]="zitiertes";
$o[45][3]="zitierender";
$o[45][4]="zitiert";

$q[46][1]="A: Paul hatte einen schrecklichen Skiunfall.";
$q[46][2]="B: Ach, so wie ich ihn kenne,_____ das nicht so schlimm _____ _____ ."; 

$o[46][1]="wird ... gewesen sein";
$o[46][2]="wird ... gewesen haben";
$o[46][3]="werden ... gewesen sein";
$o[46][4]="war ... gewesen";

$q[47][1]="Mark fliegt garantiert von der Schule, wenn er nicht aufhört die Lehrer zu ______.";

$o[47][1]="lamentieren";
$o[47][2]="profilieren";
$o[47][3]="provozieren";
$o[47][4]="negieren";

$q[48][1]="A: Hast du schon eine neue Stelle gefunden?";
$q[48][2]="B: Ja, kurz nachdem wir aus Australien _____ _____, fand ich eine neue Stelle.";

$o[48][1]="zurückgekommen ... hatten";
$o[48][2]="zurückkommen ... waren";
$o[48][3]="zurückgekommen ... haben";
$o[48][4]="zurückgekommen ... waren";

$q[49][1]="A: Ich gehe zum Einkaufen!";
$q[49][2]="B: Warte,schreib dir eine Liste,  ____________ du einkaufen gehst!";

$o[49][1]="bevor";
$o[49][2]="seit";
$o[49][3]="seitdem";
$o[49][4]="während";

$q[50][1]="A: Die ersten Teilprüfungen waren ____ leicht";
$q[50][2]="B: Die nächten Examen werden garantiert schwieriger.";

$o[50][1]="gar";
$o[50][2]="halbwegs";
$o[50][3]="überhaupt";
$o[50][4]="mal";










$a[1]="d";
$a[2]="b";
$a[3]="a";
$a[4]="d";
$a[5]="c";
$a[6]="b";
$a[7]="c";
$a[8]="a";
$a[9]="c";
$a[10]="c";
$a[11]="b";
$a[12]="d";
$a[13]="c";
$a[14]="d";
$a[15]="c";
$a[16]="b";
$a[17]="a";
$a[18]="b";
$a[19]="c";
$a[20]="a";
$a[21]="c";
$a[22]="b";
$a[23]="d";
$a[24]="a";
$a[25]="b";
$a[26]="a";
$a[27]="d";
$a[28]="c";
$a[29]="b";
$a[30]="b";
$a[31]="a";
$a[32]="c";
$a[33]="b";
$a[34]="c";
$a[35]="c";
$a[36]="b";
$a[37]="d";
$a[38]="a";
$a[39]="b";
$a[40]="c";
$a[41]="a";
$a[42]="b";
$a[43]="d";
$a[44]="a";
$a[45]="b";
$a[46]="a";
$a[47]="c";
$a[48]="d";
$a[49]="a";
$a[50]="b";
?>
