<?php
$responses=array(1=>'a','b','c','d');

$language_lower="italienisch";
$language_upper="Italienisch";
$target_langDE="Italienisch";
$title="Einstufungstest f&uuml;r Italienisch";
$question_word="Domanda";

$q[1][1]="A: Ciao, mi chiamo Marta. E tu come ____";
$q[1][2]="B: Davide.";

$o[1][1]="Vi chiamate";
$o[1][2]="ci chiamiamo";
$o[1][3]="si chiama";
$o[1][4]="ti chiami";

$q[2][1]="A: Scusi, Lei che lavoro_____?";
$q[2][2]="B: faccio la casalinga. ";

$o[2][1]="fai";
$o[2][2]="fa";
$o[2][3]="fanno";
$o[2][4]="facciamo";

$q[3][1]="A: Buongiorno. Desiderano?";
$q[3][2]="B: Dunque,io _____ un caffè.";

$o[3][1]="vorrei";
$o[3][2]="volere";
$o[3][3]="mangio";
$o[3][4]="abbiamo";

$q[4][1]="A: Scusi, che ore_____?";
$q[4][2]="B:_____ le quattro e mezza.";

$o[4][1]="é... sono";
$o[4][2]="sono... é";
$o[4][3]="sei... sono";
$o[4][4]="sono... sono";

$q[5][1]="A: Buongiorno. Ho una camera_____. Mi chiamo Paccini."; 
$q[5][2]="B: Sí, una camera doppia____ una notte.";

$o[5][1]="prenotato... da";
$o[5][2]="avuta... in";
$o[5][3]="prenotata... per";
$o[5][4]="dato... a";

$q[6][1]="A: A che ora____ la colazione?";
$q[6][2]="B: La colazione é____ 7:30____ 10:00";

$o[6][1]="sono... nelle...fino...";
$o[6][2]="é... dalle... fino alle";
$o[6][3]="é... alle... in";
$o[6][4]="sono... dalle... fino alle";

$q[7][1]="A: Scusi, mi puó dire dov´é Piazza Navona?.";
$q[7][2]="B: Mi dispiace, non___ so perché non sono di qui.";

$o[7][1]="la";
$o[7][2]="il";
$o[7][3]="lo";
$o[7][4]="le";

$q[8][1]="A: Dov´é la chiesa di S.Giacomo?.";
$q[8][2]="B: La chiesa é accanto____ farmacia";

$o[8][1]="alla";
$o[8][2]="della";
$o[8][3]="dalla";
$o[8][4]="al";

$q[9][1]="A: Ho saputo che hai fatto un viaggio.Dove _____ di bello?";
$q[9][2]="B: Ho______ il castello di San Leo.";

$o[9][1]="sei... ero";
$o[9][2]="sei stata... avere";
$o[9][3]="sei andata... visitato";
$o[9][4]="sei andata... visitare";

$q[10][1]="A: Il viaggio ti __ piaciut_?";
$q[10][2]="B: Sí, tantissimo.";

$o[10][1]="sono... piaciute";
$o[10][2]="sono... piaciuti";
$o[10][3]="é... piaciuto";
$o[10][4]="é... piaciuta";

$q[11][1]="A: Cosa ___ consiglia per pranzo?";
$q[11][2]="B: Oggi____ penne all´arrabiata e orecchiette al pesto.";

$o[11][1]="ci... mangia";
$o[11][2]="ci... ci sono";
$o[11][3]="si... hanno";
$o[11][4]="ne... c´é";

$q[12][1]="A: La bistecca come___ vuole?";
$q[12][2]="B: Al sangue, per cortesia.";

$o[12][1]="lo";
$o[12][2]="le";
$o[12][3]="il";
$o[12][4]="la";

$q[13][1]="A: Che cosa _______?";
$q[13][2]="B: ______ il sole.";

$o[13][1]="stai fare... prendo";
$o[13][2]="stai facendo... sto";
$o[13][3]="stai facendo... sto prendendo";
$o[13][4]="sei... sto prendendo";

$q[14][1]="A: Ciao Marco,______ a pranzo?";
$q[14][2]="B: No, mi dispiace.______ studiare.";

$o[14][1]="ti fermi... possa";
$o[14][2]="ti vieni... devo";
$o[14][3]="viene... devo";
$o[14][4]="ti fermi... devo";

$q[15][1]="A: Ho _____ che sei_____ in Francia.";
$q[15][2]="B: Sí, due settimane fa.";

$o[15][1]="sapevo... stato";
$o[15][2]="sapere... stato";
$o[15][3]="saputo... stato";
$o[15][4]="saputo... stare";

$q[16][1]="A: Al Club____ _____ indipendenti e felici.";
$q[16][2]="B: È vero,______ ____ indipendente e felice.";

$o[16][1]="tutti é... ognuno sono";
$o[16][2]="tutti sono... ognuno é";
$o[16][3]="ognuno é... tutti sono";
$o[16][4]="ognuno sono... tutti é";

$q[17][1]="Volevo fare una sauna, solo che___ ____ presa un raffreddore.";

$o[17][1]="mi sono";
$o[17][2]="si sono";
$o[17][3]="si é";
$o[17][4]="mi é";

$q[18][1]="A: Ho comprato dei dolci ____ mamma";
$q[18][2]="B: Ah, ___ sono piaciuti?";

$o[18][1]="al... gli";
$o[18][2]="alla... le";
$o[18][3]="ai... le";
$o[18][4]="alle... gli";

$q[19][1]="A: Senta, ho visto quei pantaloni grigi in vetrina. Posso provar__?";
$q[19][2]="B: Certo, che ____________";

$o[19][1]="provarlo... cosa fa";
$o[19][2]="provarla... taglia volere";
$o[19][3]="provarli... taglia porta";
$o[19][4]="provarle... ore sono";

$q[20][1]="A: Quanto _____ questa camicia";
$q[20][2]="B: La camicia costa 120€.";

$o[20][1]="viene";
$o[20][2]="vengono";
$o[20][3]="sono";
$o[20][4]="vieni";

$q[21][1]="A: È giá arrivato ______ ?";
$q[21][2]="B: No, non é ancora arrivato ____.";

$o[21][1]="qualcuna... niente";
$o[21][2]="sono... niente";
$o[21][3]="qualcuno... nessuno";
$o[21][4]="qualche... alcuno";

$q[22][1]="A: Quante torte hai fatto?";
$q[22][2]="B: ___ ho fatte una dozzina e __ ho portate tutte.";

$o[22][1]="ci... le";
$o[22][2]="ne... le";
$o[22][3]="ne... gli";
$o[22][4]="le... loro";

$q[23][1]="Titanic é un film ___ ho visto almeno 5volte.";

$o[23][1]="in cui";
$o[23][2]="a cui";
$o[23][3]="con cui";
$o[23][4]="che";

$q[24][1]="A: Quanto ____ il viaggio?";
$q[24][2]="B: Da Milano a Roma_____ almeno 6ore";

$o[24][1]="dura... ci vogliono";
$o[24][2]="vogliamo... dura";
$o[24][3]="vogliono... durano";
$o[24][4]="durano... ci vuole";

$q[25][1]="A che facoltá __ ____ iscritto?";

$o[25][1]="ti sono";
$o[25][2]="ti sei";
$o[25][3]="ci sei";
$o[25][4]="si sono";

$q[26][1]="Fabio non si __ potuto laureare, perché __ voluto sposar__.";

$o[26][1]="é... ha... sposarsi";
$o[26][2]="é... sono... sposare";
$o[26][3]="sono... ha... sposarsi";
$o[26][4]="sono... sono... sposarsi";

$q[27][1]="Sono andato dal dottore e mi ha detto che _____ fumare di meno.";

$o[27][1]="dovessi";
$o[27][2]="avendo dovuto";
$o[27][3]="dovendo";
$o[27][4]="dovrei";

$q[28][1]="Tu dici sempre che le vacanze é _____ passarle al mare: quale posto_______ della Sardegna?";

$o[28][1]="migliore... meglio";
$o[28][2]="il migliore... al meglio";
$o[28][3]="meglio... migliore";
$o[28][4]="al meglio... il migliore";

$q[29][1]="Ho lasciato l´arrosto in tavola.________ altrimenti si raffredda";

$o[29][1]="Mangiali";
$o[29][2]="Mangialo";
$o[29][3]="Mangiano";
$o[29][4]="Mangi";

$q[30][1]="A: Posso chiudere la finestra?";
$q[30][2]="B: No, non______ perché poi fa caldo.";

$o[30][1]="chiedere";
$o[30][2]="chiuderla";
$o[30][3]="chiuderlo";
$o[30][4]="chiuderli";

$q[31][1]="A: Hai voglia di andare al cinema stasera?";
$q[31][2]="B: Ma sai,_______ sono un po´stanca, meglio andarci domani.";

$o[31][1]="Il fatto é che";
$o[31][2]="ci pensi Lei!";
$o[31][3]="D´accordo";
$o[31][4]="Non si preoccupi";

$q[32][1]="A: Sul mio tavolo ci sono delle lettere in inglese,_______ subito in italiano per favore";

$o[32][1]="ne traduca";
$o[32][2]="lo traduce";
$o[32][3]="le traduca";
$o[32][4]="li traduca";

$q[33][1]="A: Com´erano i dolci di Maria?";
$q[33][2]="B: Non li ho assaggiati perché me ne ____ andata proprio mentre li____.";

$o[33][1]="ho... prepara";
$o[33][2]="sono... preparava";
$o[33][3]="sono... preparato";
$o[33][4]="ero... prepara";

$q[34][1]="Se preferisce _______ di elegante ____ l´abito di Valentino.";

$o[34][1]="bello... ci sono";
$o[34][2]="qualcosa... ci sono";
$o[34][3]="qualcosa... c´é";
$o[34][4]="quello... c´é";

$q[35][1]="La ditta____ lavoro, é molto importante.";

$o[35][1]="a cui";
$o[35][2]="con che";
$o[35][3]="per cui";
$o[35][4]="la quale";

$q[36][1]="A: Posso indossare il tuo vestito stasera?";
$q[36][2]="B: Sí certo, __ ___ presto volentieri.";

$o[36][1]="lo te";
$o[36][2]="te lo";
$o[36][3]="glielo";
$o[36][4]="loro lo";

$q[37][1]="L´auto non parte piú. Si_____ _____ rotto il motore.";

$o[37][1]="deve volere";
$o[37][2]="vuole essere";
$o[37][3]="deve essersi";
$o[37][4]="deve essere";

$q[38][1]="Penso che__ _____ piú rispetto per le persone";

$o[38][1]="ci voglia";
$o[38][2]="con voglia";
$o[38][3]="vi vuole";
$o[38][4]="ne vuole";

$q[39][1]="Gli studenti______ meglio a studiare di piú.";

$o[39][1]="avere fatto";
$o[39][2]="avrebbero fatto";
$o[39][3]="avrebbero dato";
$o[39][4]="hanno dato";

$q[40][1]="Dopo____ _____, ha deciso di prendersi una vacanza.";

$o[40][1]="avere laureata";
$o[40][2]="essersi laureare";
$o[40][3]="essersi laureata";
$o[40][4]="avere laurearsi";

$q[41][1]="Avevi promesso che______";

$o[41][1]="saremmo usciti";
$o[41][2]="fossimo usciti";
$o[41][3]="uscimmo";
$o[41][4]="usciremo";

$q[42][1]="A: Paola ha deciso che vuole sposare Marco invece di Luca.";
$q[42][2]="B: bé l´importante é che_______ .";

$o[42][1]="sposa";
$o[42][2]="si sposi";
$o[42][3]="si sposare";
$o[42][4]="sposare";

$q[43][1]="Si é mostrato sicuro di sé come se ______ tutto lui.";

$o[43][1]="sapeva";
$o[43][2]="sappia";
$o[43][3]="sapevano";
$o[43][4]="sapesse";

$q[44][1]="Marco ha bisogno di un amico che ___ ______.";

$o[44][1]="lo capisse";
$o[44][2]="lo capiva";
$o[44][3]="lo capisca";
$o[44][4]="capiva";

$q[45][1]="Ci si augurava che il non______ male.";

$o[45][1]="finiscono";
$o[45][2]="finisse";
$o[45][3]="finiva";
$o[45][4]="finiva";

$q[46][1]="A: Vuoi venire con noi a teatro?";
$q[46][2]="B: Mi dispiace, mel´hai detto troppo tardi. Se______ prima, sarei venuta volentieri.";

$o[46][1]="mel´avessi detto";
$o[46][2]="mi diceva";
$o[46][3]="me lo dicessi";
$o[46][4]="me la dicevi";

$q[47][1]="Gli ho fatto notare quanto ________ arrogante rispondere in quel modo.";

$o[47][1]="sono";
$o[47][2]="erano";
$o[47][3]="fosse";
$o[47][4]="fare";

$q[48][1]="A: Aspetta, prendo l´ombrello.";
$q[48][2]="B: Che________, non vedi che c´é il sole?";

$o[48][1]="prendete a fare";
$o[48][2]="lo prendere fare";
$o[48][3]="fare";
$o[48][4]="lo prendi a fare";


$a[1]="d";
$a[2]="b";
$a[3]="a";
$a[4]="d";
$a[5]="c";
$a[6]="b";
$a[7]="c";
$a[8]="a";
$a[9]="c";
$a[10]="c";
$a[11]="b";
$a[12]="d";
$a[13]="c";
$a[14]="d";
$a[15]="c";
$a[16]="b";
$a[17]="a";
$a[18]="b";
$a[19]="c";
$a[20]="a";
$a[21]="c";
$a[22]="b";
$a[23]="d";
$a[24]="a";
$a[25]="b";
$a[26]="a";
$a[27]="d";
$a[28]="c";
$a[29]="b";
$a[30]="b";
$a[31]="a";
$a[32]="c";
$a[33]="b";
$a[34]="c";
$a[35]="c";
$a[36]="b";
$a[37]="d";
$a[38]="a";
$a[39]="b";
$a[40]="c";
$a[41]="a";
$a[42]="b";
$a[43]="d";
$a[44]="c";
$a[45]="b";
$a[46]="a";
$a[47]="c";
$a[48]="d";
?>
