<?php

/*
lang [ test language, page language ]
*/

$lang = array(
	"english" => array (
		"EN" => "English",
		"DE" => "Englisch",
		"FR" => "anglais",
		"IT" => "Inglese",
		"ES" => "Inglés"
	),
	"deutsch" => array (
		"EN" => "German",
		"DE" => "Deutsch",
		"FR" => "allemand",
		"IT" => "Tedesco",
		"ÉS" => "alemán"
	),
	"french" => array (
		"EN" => "French",
		"DE" => "Französisch",
		"FR" => "français",
		"IT" => "francese",
		"ES" => "francés"
	),
	"italian" => array (
		"EN" => "Italian",
		"DE" => "Italienisch",
		"FR" => "italien",
		"IT" => "italiano",
		"ES" => "italiano"
	),
	"spanish" => array (
		"EN" => "Spanish",
		"DE" => "Spanisch",
		"FR" => "espanol",
		"IT" => "spagnolo",
		"ES" => "Español"
	)
);
?>
