<?php
$responses=array(1=>'a','b','c','d');

$language_lower="spanisch";
$language_upper="Spanisch";
$target_langDE="Spanisch";
$title="Einstufungstest f&uuml;r Spanisch";
$question_word="Cuestión";


$q[1][1]="A: Hola, me llamo Sandra. Y tú, ¿cómo te______?";

$o[1][1]="llamo";
$o[1][2]="llaman";
$o[1][3]="llama";
$o[1][4]="llamas";

$q[2][1]="A: ¿ ______ se dice “Krankenhaus” en español?";
$o[2][2]="B: Se dice “hospital”.";

$o[2][1]="Quién";
$o[2][2]="Cómo";
$o[2][3]="Dónde";
$o[2][4]="Qué";

$q[3][1]="A: Y Julio, ¿en qué trabaja?";
$q[3][2]="B: Julio es______  del Banco Santander.";

$o[3][1]="empleado";
$o[3][2]="veterinario";
$o[3][3]="secretaria";
$o[3][4]="profesor ";

$q[4][1]="Pedro vive en Méjico, pero sus padres ______ en Chile.";

$o[4][1]="vives";
$o[4][2]="vive";
$o[4][3]="vivo";
$o[4][4]="viven";

$q[5][1]="¿Cuál ______ tu número de teléfono?";

$o[5][1]="está";
$o[5][2]="tienes";
$o[5][3]="es";
$o[5][4]="hay";

$q[6][1]="En Valladolid _____ una iglesia muy bonita.";

$o[6][1]="es";
$o[6][2]="hay";
$o[6][3]="son";
$o[6][4]="está";

$q[7][1]="Perdone,¿dónde  ______ el Teatro Dilo?";

$o[7][1]="hay";
$o[7][2]="están";
$o[7][3]="está";
$o[7][4]="es";

$q[8][1]="A: ¿Te_______ hacer deporte?";
$q[8][2]="B: Pues la verdad es que no.______ ir a bailar.";

$o[8][1]="gusta / Prefiero";
$o[8][2]="gusto / Prefiere";
$o[8][3]="gustan / Prefiero";
$o[8][4]="gustas / Prefieres";

$q[9][1]="A: Buenos días, señora.¿Qué desea?";
$q[9][2]="B: ¿ _____ aceite de oliva?";

$o[9][1]="Deme";
$o[9][2]="Quiere";
$o[9][3]="Tiene";
$o[9][4]="Cómo";

$q[10][1]="A: Un kilo de tomates, por favor.";
$q[10][2]="B: ¿Cómo  _______ quiere?";
$q[10][3]="A: No muy verdes.";

$o[10][1]="los";
$o[10][2]="les";
$o[10][3]="las";
$o[10][4]="la";

$q[11][1]="A: ¿Qué tal está el pollo?";
$q[11][2]="B: Está   ________ rico.";

$o[11][1]="mucho";
$o[11][2]="muy";
$o[11][3]="poco";
$o[11][4]="demasiado";

$q[12][1]="A: No me gusta la música clásica.";
$q[12][2]="B: __________________ .";

$o[12][1]="A mí no";
$o[12][2]="Yo no";
$o[12][3]="Yo tampoco";
$o[12][4]="A mí tampoco";

$q[13][1]="A Roberto _____ regalamos un disco de Madonna.";

$o[13][1]="la";
$o[13][2]="lo";
$o[13][3]="le";
$o[13][4]="los";

$q[14][1]="A: Bueno, chicos, ¿qué queréis tomar?";
$q[14][2]="B: ____  dos zumos de naranja.";

$o[14][1]="Queremos";
$o[14][2]="Quieres";
$o[14][3]="Querían";
$o[14][4]="Quieren";

$q[15][1]="Siempre me levanto a las siete. Y tú, ¿  _____levantas también tan temprano?";

$o[15][1]="se";
$o[15][2]="le";
$o[15][3]="te";
$o[15][4]="lo";

$q[16][1]="¡Por fin! Nosotros _____________ a casa.";

$o[16][1]="hemos llegados";
$o[16][2]="hemos llegado";
$o[16][3]="estamos";
$o[16][4]="estamos llegado";

$q[17][1]="Esta tarde no puedo ir al cine.______  enferma. ______  en la cama con fiebre.";

$o[17][1]="Estoy / Estoy";
$o[17][2]="Estoy / Soy";
$o[17][3]="Soy/ Soy";
$o[17][4]="Soy / Estoy";

$q[18][1]="A: Oye, Marta, ¿ ____  tomarte cuatro semanas de vacaciones? ";
$q[18][2]="B: No, la verdad es que no.";

$o[18][1]="tienes";
$o[18][2]="puedes";
$o[18][3]="juegas";
$o[18][4]="sabes";

$q[19][1]="La semana pasada  __________ al pueblo de mi abuela.";

$o[19][1]="he ido";
$o[19][2]="iba";
$o[19][3]="fui";
$o[19][4]="voy";

$q[20][1]="A: Buenos días. ¿Qué va a tomar?";
$q[20][2]="B: Yo  ____ quiero una ensalada, de segundo pescado y ______ helado.";

$o[20][1]="de primero / de postre";
$o[20][2]="el primero / el postre";
$o[20][3]="de primero / al postre";
$o[20][4]="el primero / de postre";

$q[21][1]="Tienes que poner______ (la camisa).";

$o[21][1]="la";
$o[21][2]="le";
$o[21][3]="tela";
$o[21][4]="selo";

$q[22][1]="A Marta______ gusta mucho comer queso de cabra";

$o[22][1]="se";
$o[22][2]="le";
$o[22][3]="te";
$o[22][4]="la";

$q[23][1]="El Sr. Romero _____ en Madrid desde 1986 hasta 1990.";

$o[23][1]="viví";
$o[23][2]="vive";
$o[23][3]="vivía";
$o[23][4]="vivió";

$q[24][1]="Mariana _____ sus estudios de Medicina el año pasado con muy buenas notas.";

$o[24][1]="terminó";
$o[24][2]="término";
$o[24][3]="terminé";
$o[24][4]="termino";

$q[25][1]="Cuando_____ pequeña, ______ con mis amigas en el parque.";

$o[25][1]="era/ jugué";
$o[25][2]="era/ jugaba";
$o[25][3]="era/ he jugado";
$o[25][4]="fui/ jugaba";

$q[26][1]="_____ 3 años trabajo en esta empresa";

$o[26][1]="Desde hace";
$o[26][2]="Desde";
$o[26][3]="Hace";
$o[26][4]="Hace desde";

$q[27][1]="A: ¡Ana! Mira, te presento a Luis, mi jefe.";
$q[27][2]="B: _______.";

$o[27][1]="Me gusta mucho";
$o[27][2]="Me encanta";
$o[27][3]="Me gusto";
$o[27][4]="Encantada";

$q[28][1]="Yo me voy ____________aquí. Hay mucho ruido.";

$o[28][1]="fuera";
$o[28][2]="a";
$o[28][3]="de";
$o[28][4]="en";

$q[29][1]="Sonia trabaja ____________.";

$o[29][1]="demasiada";
$o[29][2]="nada";
$o[29][3]="demasiado";
$o[29][4]="muy";

$q[30][1]="Ya estoy a punto de ____________el libro que me regalaste.";

$o[30][1]="termina";
$o[30][2]="terminar";
$o[30][3]="terminando";
$o[30][4]="terminado";

$q[31][1]="A: Bueno, ¿vienes con nosotros o no?";
$q[31][2]="B: Pues ahora no puedo.   _____la lámpara de la cocina.";  

$o[31][1]="Estoy arreglando";
$o[31][2]="He arreglado";
$o[31][3]="Estoy arreglado";
$o[31][4]="Arreglo";

$q[32][1]="A: ¿Cuándo has llegado _______Berlín?";
$q[32][2]="B: Esta mañana.";

$o[32][1]="hacia";
$o[32][2]="para";
$o[32][3]="a";
$o[32][4]="en";

$q[33][1]="Primero hice la pizza y _______nos la comimos entre todos.";

$o[33][1]="antes";
$o[33][2]="luego";
$o[33][3]="después de";
$o[33][4]="durante";

$q[34][1]="Mi departamento no es_______grande _______ el tuyo.";

$o[34][1]="tanto ..... como";
$o[34][2]="tan ..... que";
$o[34][3]="tan ..... como";
$o[34][4]="tanto ..... que";

$q[35][1]="A: Mamá, ¿puedo jugar un rato más?";
$q[35][2]="B: Claro que sí.________todo el tiempo que quieras."; 

$o[35][1]="jugar";
$o[35][2]="juege";
$o[35][3]="juega";
$o[35][4]="juegas";

$q[36][1]="Mi hermano _______ahora que quiere estudiar Geografía.";

$o[36][1]="dices";
$o[36][2]="dice";
$o[36][3]="dije";
$o[36][4]="deje";

$q[37][1]="A: ¿Vamos a tu casa a comer?";
$q[37][2]="B: No, mejor no. _______no he hecho la compra y no tengo nada en el frigorífico.";

$o[37][1]="Ayer";
$o[37][2]="La semana pasada";
$o[37][3]="El otro día";
$o[37][4]="Esta semana";

$q[38][1]="Cuando________jóvenes nos gustaba mucho ir a la playa.";

$o[38][1]="éramos";
$o[38][2]="erais";
$o[38][3]="estábamos";
$o[38][4]="estabais";

$q[39][1]="Por favor, Sra. López,_______asiento.";

$o[39][1]="toma";
$o[39][2]="tome";
$o[39][3]="tomas";
$o[39][4]="tomó";

$q[40][1]="A: ¿Qué hiciste ayer por la tarde?";
$q[40][2]="B: Fui a un seminario.  _____  muy cansada pero no podía faltar.";

$o[40][1]="He estado";
$o[40][2]="Estuve";
$o[40][3]="Estaba";
$o[40][4]="Había estado";

$q[41][1]="¿Te han dado el trabajo? Pues ______  a tu madre, se alegrará mucho.";

$o[41][1]="díselo";
$o[41][2]="dile";
$o[41][3]="di";
$o[41][4]="dilo";

$q[42][1]="A: ¿Cuántos huevos hay en la nevera?";
$q[42][2]="B:  ________  tres.";

$o[42][1]="Me quedo";
$o[42][2]="Quedan";
$o[42][3]="Quedo";
$o[42][4]="Queda";

$q[43][1]="Nunca olvidaré ________  pasó aquel verano.";

$o[43][1]="todo el que";
$o[43][2]="todo que";
$o[43][3]="nada que";
$o[43][4]="todo lo que";

$q[44][1]="A: Dime, María, ¿dónde serán tus próximas vacaciones?";
$q[44][2]="B: Pues mira, me_____  ir cerca del mar.";

$o[44][1]="encantaría";
$o[44][2]="soportaría";
$o[44][3]="encantaba";
$o[44][4]="soportaba";

$q[45][1]="A: El profesor quiere que _______ para el examen final.";
$q[45][2]="B: Pues yo no sé si voy a tener tiempo.";

$o[45][1]="estudiarán";
$o[45][2]="estudiemos";
$o[45][3]="estudiariamos";
$o[45][4]="estudiamos";

$q[46][1]="A: ¿Qué hizo usted la noche del incendio?";
$q[46][2]="B:  Aquella noche  ______  a casa de un amigo a ver una película.Sus compañeros de piso no________ .";

$o[46][1]="fui/ estaban";
$o[46][2]="fui / estuvieron";
$o[46][3]="iba / estaban";
$o[46][4]="iba/ estuvieron";

$q[47][1]="A: Ayer estuve una hora esperando a Juan Luis.";
$q[47][2]="B: ¿Y por qué esperaste tanto?";
$q[47][3]="A: Porque el día anterior me dijo que  ______  un problema con su jefe y me lo quería contar.";

$o[47][1]="ha tenido";
$o[47][2]="haya tenido";
$o[47][3]="había tenido";
$o[47][4]="habría tenido";

$q[48][1]="A: ¿Por qué te has enfadado tanto con tu hermana?";
$q[48][2]="B:  Porque siempre usa mi pantalón nuevo y sabe que eso me  _________  mucho.";

$o[48][1]="pone triste";
$o[48][2]="emociona";
$o[48][3]="divierte";
$o[48][4]="molesta";

$q[49][1]="Espero que el equipo de fútbol se  ____________  para las Olimpiadas.";

$o[49][1]="clasifique";
$o[49][2]="clasificará";
$o[49][3]="clasificaría";
$o[49][4]="clasifica";

$q[50][1]="Imagínate que en la lotería ganas un millón de euros ¿Qué_____  con tanto dinero?";

$o[50][1]="has hecho";
$o[50][2]="harías";
$o[50][3]="hagas";
$o[50][4]="hacías";

$q[51][1]="A: ¿Te parece  ir el jueves al concierto de Juanes?";
$q[51][2]="B: Lo siento, pero no puedo.  ____  tengo entrenamiento.";

$o[51][1]="Los jueves";
$o[51][2]="En jueves";
$o[51][3]="Al jueves";
$o[51][4]="Jueves";

$q[52][1]="Mónica, ya sabes que puedes contar conmigo para lo que ____________  . No importa lo que sea.";

$o[52][1]="querrías";
$o[52][2]="quieras";
$o[52][3]="quieres";
$o[52][4]="querías";

$q[53][1]="La conservación de la contaminación ambiental es un tema que me preocupa. _________  he decidido estudiar Ciencias Ambientales.";

$o[53][1]="Sin embargo";
$o[53][2]="Por eso";
$o[53][3]="Ahora bien";
$o[53][4]="En cuanto a eso";

$q[54][1]="A: Hola, buenos días ¿Estaría usted interesado  ____  un nuevo producto de Alimentación?";
$q[54][2]="B: Pues mire, no, muchas gracias.";

$o[54][1]="a";
$o[54][2]="por";
$o[54][3]="en";
$o[54][4]="para";

$q[55][1]="Distinguido Sr. Gutiérrez: Aquí le mando el pedido  que nos pidió. Gracias por confiar en “La tortuga rápida”.
           ________ .Julio Romero Valdés";

$o[55][1]="Recuerdos a tu madre";
$o[55][2]="Un fuerte abrazo";
$o[55][3]="Saludos amistosos";
$o[55][4]="Un cordial saludo";

$q[56][1]="No es verdad que me  _________  a comprar un ordenador nuevo.";

$o[56][1]="voy";
$o[56][2]="iré";
$o[56][3]="vaya";
$o[56][4]="he ido";

$q[57][1]="Bueno dime, ¿qué te parece la nueva compañera? Pues, __________ , me cae fatal.";

$o[57][1]="sinceramente";
$o[57][2]="por suerte";
$o[57][3]="de todos modos";
$o[57][4]="para colmo";

$q[58][1]="_________  Macarena se haya casado, no me lo creo.";

$o[58][1]="Eso de";
$o[58][2]="Lo que";
$o[58][3]="Eso de que";
$o[58][4]="Lo de";

$q[59][1]="A: Cuando _______  de trabajar, te visitaré.";
$q[59][2]="B: Ya, eso dices siempre y luego nunca llegas.";

$o[59][1]="termine";
$o[59][2]="terminara";
$o[59][3]="termino";
$o[59][4]="terminaré";

$q[60][1]="De haber sabido que tú tenías el libro de Isabel Allende, no me lo__________ .";

$o[60][1]="comprara";
$o[60][2]="haya comprado";
$o[60][3]="compraría";
$o[60][4]="habría comprado";

$q[61][1]="Los directivos de la empresa se han comprometido __________ cumplir el contrato. Ya veremos qué pasa.";

$o[61][1]="a";
$o[61][2]="de";
$o[61][3]="para";
$o[61][4]="por";

$q[62][1]="Pedro no quiere___________  con sus nuevos vecinos. Al parecer son muy curiosos.";

$o[62][1]="relacionarse";
$o[62][2]="que se relaciona";
$o[62][3]="que se relacione";
$o[62][4]="relacionándose";

$q[63][1]="Cuando escuché su tono de voz por teléfono, supe  _________  que algo había sucedido.";

$o[63][1]="en esos momentos";
$o[63][2]="inmediatamente";
$o[63][3]="de golpe";
$o[63][4]="mientras";

$q[64][1]="A: Dime ¿sabes qué significa “taquillera”?";
$q[64][2]="B: Sí, creo que es la persona  _______  le compras las entradas para el cine.";

$o[64][1]="para que";
$o[64][2]="que";
$o[64][3]="a que";
$o[64][4]="a la que";

$q[65][1]="El verano pasado no llovió practicamente nada y tuvimos una de las_________ más preocupantes de los últimos años.";

$o[65][1]="heladas";
$o[65][2]="sequías";
$o[65][3]="vendavales";
$o[65][4]="inundaciones";

$q[66][1]="¿Cómo queréis ir a Argentina?_______  en avión siempre y cuando el precio fuera razonable.";

$o[66][1]="Iríamos";
$o[66][2]="Vayamos";
$o[66][3]="Iremos";
$o[66][4]="Fueramos";

$q[67][1]="Que los países _______  programas para la construcción de armamento nuclear, me parece realmente preocupante.";

$o[67][1]="desarrollarían";
$o[67][2]="desarrollaran";
$o[67][3]="desarrollen";
$o[67][4]="desarrollan";

$q[68][1]="Ella pensaba que su novio se _______  mucho. Por eso le organizó una fiesta sorpresa.";

$o[68][1]="alegraría";
$o[68][2]="alegre";
$o[68][3]="alegraba";
$o[68][4]="alegró";

$q[69][1]="A: ¿Hay alguien que _____  japonés en esta oficina?";
$q[69][2]="B: Creo que no.";

$o[69][1]="hablaría";
$o[69][2]="hablase";
$o[69][3]="hable";
$o[69][4]="habla";

$q[70][1]="El aceite es un alimento muy sano. ________ reduce el nivel de colesterol, ayuda a prevenir enfermedades.";

$o[70][1]="A pesar de que";
$o[70][2]="Puesto que";
$o[70][3]="Sin embargo";
$o[70][4]="Aunque";















$a[1]="d";
$a[2]="b";
$a[3]="a";
$a[4]="d";
$a[5]="c";
$a[6]="b";
$a[7]="c";
$a[8]="a";
$a[9]="c";
$a[10]="a";
$a[11]="b";
$a[12]="d";
$a[13]="c";
$a[14]="a";
$a[15]="c";
$a[16]="b";
$a[17]="a";
$a[18]="b";
$a[19]="c";
$a[20]="a";
$a[21]="c";
$a[22]="b";
$a[23]="d";
$a[24]="a";
$a[25]="b";
$a[26]="a";
$a[27]="d";
$a[28]="c";
$a[29]="b";
$a[30]="b";
$a[31]="a";
$a[32]="c";
$a[33]="b";
$a[34]="c";
$a[35]="c";
$a[36]="b";
$a[37]="d";
$a[38]="a";
$a[39]="b";
$a[40]="c";
$a[41]="a";
$a[42]="b";
$a[43]="d";
$a[44]="a";
$a[45]="b";
$a[46]="a";
$a[47]="c";
$a[48]="d";
$a[49]="a";
$a[50]="b";
$a[51]="a";
$a[52]="b";
$a[53]="b";
$a[54]="c";
$a[55]="d";
$a[56]="c";
$a[57]="a";
$a[58]="c";
$a[59]="a";
$a[60]="d";
$a[61]="a";
$a[62]="a";
$a[63]="a";
$a[64]="d";
$a[65]="b";
$a[66]="a";
$a[67]="c";
$a[68]="a";
$a[69]="c";
$a[70]="b";














?>
