<?php
$title_head0 = "Placement Test";
$title_head1 = "Personal Data";
$title_head2 = "Availability";
$title_head3 = "Needs Analysis";
$title_head4 = "Self Evaluation";
if (isset($target_lang_type)) {
  $title_head5 = "Placement Test for ".$target_lang_type." ".$target_lang;
}
else {
  $title_head5 = "Placement Test for ".$target_lang;
}


$title_firm = "Company Name";
$title_surname = "Family Name";
$title_vorname = "Given Name";
$title_email = "Email";
$title_telbus = "Telephone (Business)";
$title_telmob = "Telephone (Mobile)";

$title_wunschtermine = "Ideal appointments (time/day)";
$title_moeglichetermine = "Other possible appointments (time/day)";
$title_nichtmoeglichetermine = "Appointments to avoid (time/day)";

$title_beruf = "Profession";
$title_position = "Position";

$title_question1 = "Do you regularly speak ".$target_lang."?";
$title_question2 = "Which topics and which vocabulary are important to you?";
$title_question3 = "In which situations do you have difficulties speaking ".$target_lang."?";
$title_question4 = "In which situations do you speak ".$target_lang." / for which situations do you need ".$target_lang."?";

$title_selbst = "I estimate my spoken language skills as following (please select)";

$title_submit = "Submit test to MODOLINGO";

?>

