<?php

$title_head0 = "Einstufungstest";
$title_head1 = "Pers&ouml;nliche Daten";
$title_head2 = "Verfügbarkeiten";
$title_head3 = "Bedarfsanalyse";
$title_head4 = "Selbsteinschätzung";
if (isset($target_lang_type)) {
  $title_head5 = "Winstufungstest für ".$target_lang_type." ".$target_lang;
}
else {
  $title_head5 = "Einstufungstest für ".$target_lang;
}


$title_firm = "Firma";
$title_surname = "Name";
$title_vorname = "Vorname";
$title_email = "Email";
$title_telbus = "Telefon (gesch&auml;ftlich)";
$title_telmob = "Telefon (Mobil)";

$title_wunschtermine = "Meine Wunschtermine (Tage/Uhrzeiten)";
$title_moeglichetermine = "Folgende Termine sind notfalls für mich ebenfalls möglich (Tage/Uhrzeiten)";
$title_nichtmoeglichetermine = "Folgende Termine sind für mich nicht möglich (Tage/Uhrzeiten)";

$title_beruf = "Beruf";
$title_position = "Position";

$title_question1 = "Sprechen Sie regelmäßig ".$target_lang."?";
$title_question2 = "Welche Inhalte und welcher Wortschatz sind für Sie wichtig?";
$title_question3 = "In welchen Situationen haben Sie Schwierigkeiten, ".$target_lang." zu sprechen?";
$title_question4 = "In welchen Situationen sprechen Sie ".$target_lang." / Für welche Situationen benötigen Sie ".$target_lang."?";

$title_selbst = "Ich schätze meine mündlichen Sprachkenntnisse wie folgt ein (Zutreffendes bitte ankreuzen)";

$title_submit = "Test an MODOLINGO senden";


?>

